title: DZD Micro
author: xdaniel
timezone: Europe/Berlin

description: >
  A site for whatever long-form writing I might want to do. That is,
  things that might be longer than tweets. Like more in-depth stuff
  about programming, maybe, or computers and consoles in general.
  You know, you'll see it when it happens.

baseurl: ""
# url: "https://xdanieldzd.github.io"

twitter_username: xdanieldzd
github_username: xdanieldzd

markdown: kramdown
theme: minima
exclude:
- Gemfile
- Gemfile.lock

paginate: 3
